project:
  type: website

website:
  title: "chizo14.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: about
      
     

format:
  html:
    theme: Spacelab
    css: styles.css
    toc: true

editor: visual

